//
//  Section.swift
//  NewsReader
//
//  Created by Muneeb Ahmed Anwar on 28/08/2025.
//


public enum NewsSection: String, CaseIterable {
    case all = "all-sections"
    case arts = "arts"
    case automobiles = "automobiles"
    case books = "books"
    case briefing = "briefing"
    case business = "business"
    case climate = "climate"
    case corrections = "corrections"
    case education = "education"
    case enEspanol = "en-espanol"
    case fashion = "fashion"
    case food = "food"
    case gameplay = "gameplay"
    case guide = "guide"
    case health = "health"
    case homeAndGarden = "home-garden"
    case homePage = "home-page"
    case jobMarket = "job-market"
    case theLearningNetwork = "the-learning-network"
    case lens = "lens"
    case magazine = "magazine"
    case movies = "movies"
    case newYork = "new-york"
    case obituaries = "obituaries"
    case opinion = "opinion"
    case parenting = "parenting"
    case podcasts = "podcasts"
    case readerCenter = "reader-center"
    case realEstate = "real-estate"
    case smarterLiving = "smarter-living"
    case science = "science"
    case sports = "sports"
    case style = "style"
    case sundayReview = "sunday-review"
    case tBrand = "t-brand"
    case tMagazine = "t-magazine"
    case technology = "technology"
    case theater = "theater"
    case timesInsider = "times-insider"
    case todaysPaper = "todays-paper"
    case travel = "travel"
    case us = "us"
    case universal = "universal"
    case theUpshot = "the-upshot"
    case video = "video"
    case theWeekly = "the-weekly"
    case well = "well"
    case world = "world"
    case yourMoney = "your-money"
}
