# This workflow will build a Swift project
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Xcode Select
        run: sudo xcode-select -s /Applications/Xcode_16.app
      - name: Build & Test with Coverage
        run: |
          xcodebuild -scheme NewsReader \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -enableCodeCoverage YES \
            test
      - name: Export Coverage
        run: |
          xcrun xccov view --report --json \
            ~/Library/Developer/Xcode/DerivedData/*/Logs/Test/*.xcresult > coverage.json
      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.json
